youtube=https://www.youtube.com/
pinterest=https://ca.pinterest.com/
amazon=https://www.amazon.com/
notasite=notasite
google=https://www.google.com/
github=https://github.com/
bing=https://www.bing.com/
reddit=https://www.reddit.com/
anotherfakesite="idk"